### ISSUE TITLE
PropertyIdentifier copy-paste error

### ISSUE THREAD

**Issue by skubo** [empeeoh/BACnet4J#1]
in PropertyIdentifier.java the line 

public static final PropertyIdentifier stateDescription = new PropertyIdentifier(221);

should read 

public static final PropertyIdentifier stateDescription = new PropertyIdentifier(222);

instead. Else the load control object will not be able to render this property.

**Comment by mlohbihler** [comment]
Fixed here: https://github.com/mlohbihler/BACnet4J/commit/1157b449cab090340aa810d16ac940420fd28000
